geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


geekshop/ordersapp/urls.py
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderList.as_view(), name='main'),
    path('forming/complete/<int:pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', ordersapp.OrderItemUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', ordersapp.get_product_price),
]

geekshop/ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'
    FINISHED = 'FSD'

    ORDER_STATUS = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (FINISHED, 'завершен'),
        (CANCEL, 'отменен')
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(
        verbose_name='создан',
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        verbose_name='изменен',
        auto_now=True,
    )
    status = models.CharField(
        verbose_name='статус',
        max_length=3,
        choices=ORDER_STATUS,
        default=FORMING,
    )
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Заказ {self.user.username} №{self.id} от {self.created}'

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items))),
        }

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))


class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for obj in self:
            obj.product.quantity += obj.quantity
            obj.product.save()
        super(OrderItemQuerySet, self).delete()


class OrderItem(models.Model):
    objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(
        Order,
        related_name="orderitems",
        on_delete=models.CASCADE,
    )
    product = models.ForeignKey(
        Product,
        verbose_name='продукт',
        on_delete=models.CASCADE,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество',
        default=0,
    )

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

    def get_product_cost(self):
        return self.product.price * self.quantity

geekshop/ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = Order
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Product.objects.filter(is_active=True, quantity__gte=1)

geekshop/ordersapp/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView

from basketapp.models import Basket
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:main')

    def get_context_data(self, **kwargs):
        data = super(OrderItemCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = form.instance.product.price
                    basket_items[num].delete()
                #basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(self.__class__, self).form_valid(form)


class OrderItemUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:main')

    def get_context_data(self, **kwargs):
        data = super(OrderItemUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(self.__class__, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:main')


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:main'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()

def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk),).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

geekshop/ordersapp/templates/ordersapp/includes/ inc_order_list.html
{% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}

geekshop/ordersapp/templates/ordersapp/includes/inc_order_actions.html
{% if object.status == 'FM' %}
   <button class="btn btn-warning btn-round form-control last">
       <a href="{% url 'ordersapp:order_forming_complete' object.pk %}">
           совершить покупку
       </a>
   </button>
   <button class="btn btn-default btn-round form-control last">
       <a href="{% url 'ordersapp:order_delete' object.pk %}">удалить</a>
   </button>
{% endif %}
<button class="btn btn-info btn-round form-control last">
   <a href="{% url 'ordersapp:main' %}">
       к списку заказов
   </a>
</button>
<button class="btn btn-default btn-round form-control last">
   <a href="{% url 'main' %}">на главную</a>
</button>

geekshop/ordersapp/templates/ordersapp/includes/inc_order_list.html
{% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}

geekshop/ordersapp/templates/ordersapp/includes/inc_order_summary.html
{% if object %}
   <div class="h2">Заказ №{{ object.pk }} от {{ object.created|date:"Y-m-d H:i:s" }}</div>
   <hr>
   <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
   <div class="h4">обновлен: {{ object.updated|date:"Y-m-d H:i:s" }}</div>
   <div class="h4">cтатус: {{ object.get_status_display }}</div>
   <hr>
{%  with object_summary=object.get_summary %}
   <div class="h4">
       общее количество товаров: <span class="order_total_quantity">{{ object_summary.total_quantity }}</span>
   </div>
   <div class="h3">
       общая стоимость: <span class="order_total_cost">{{ object_summary.total_cost }}</span> руб
   </div>
    {% endwith %}
{% else %}
   <div class="h2">Новый заказ</div>
   <hr>
   <div class="h4">заказчик: {{ user.last_name }} {{ user.first_name }} </div>
   {% if basket.0 %}
       <div class="h4">
           общее количество товаров: <span class="order_total_quantity">{{ basket.0.get_total_quantity }}</span>
       </div>
       <div class="h3">
           общая стоимость: <span class="order_total_cost">{{ basket.0.get_total_cost }}</span> руб
       </div>
   {% endif %}
{% endif %}
<hr>